name: Github-Actions
on: [push, pull_request]
jobs:
  packer-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install packer
      run: ./build/ci.sh install-packer
    - name: verify packer
      run: ./build/ci.sh verify-ci

  shell-syntax-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run shellcheck
      run: ./build/ci.sh shellcheck

  shell-format-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install-shfmt
      run: ./build/ci.sh install-shfmt
    - name: run shfmt checks
      run: ./build/ci.sh shfmt
